[data_sources]
# default data source with url, username and password
default = { url = "mysql://localhost/workspace", username = "root", password = "123456" }

# data source with url only
db1 = "mysql://root:123456@localhost/workspace"

# data source with full url
db2 = "mysql://root:123456@localhost:3306/workspace"
